version: "0.0"
services:
  client:
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - server
  server:
    build: ./server
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: mysql:8.0
    ports:
      - "3308:3306"
    volumes:
      - ./db/schema.sql
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE="${MYSQL_DATABASE}"
      - MYSQL_USER="${MYSQL_USER}""
