version: "1.0"
services:
  client:
    build: .
    ports: "3000"
  server:
    build: .
    ports: 8080
    depends_on:
      - mysql
  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE="${MYSQL_DATABASE}"
      - MYSQL_USER="${MYSQL_USER}""
